### ISSUE TITLE
Generation of readthedocs with mkdocs does not work anymore

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/djutils#32]
Compilation on readthedocs.io results in a failure:

![image](https://github.com/averbraeck/djutils/assets/13779793/496ed59f-c09e-4258-972c-1eef6ee3bef1)

**Comment by averbraeck** [comment]
Note that the documentation **includes** the documentation for djutils-base.

**Comment by averbraeck** [comment]
For readthedocs, a new file called `.readthedocs.yaml` in the root directory of the project is needed, with the following content:

```yaml
# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

mkdocs:
  configuration: mkdocs.yml

# Optionally declare the Python requirements required to build your docs
python:
  install:
  - requirements: docs/requirements.txt
```

As can be seen on the last line, the file `requirements.txt` has been moved to the `docs` folder to minimize the number of files in the root folder.
