### ISSUE TITLE
Generation of site and API information does not work anymore

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/djutils#34]
The generation of the site has not been working for quite a while now. The site and javadoc should be generated using a job on one of the Delft servers.

There are a number of issues that need to be updated:

1) There might be javadoc errors... They are **not caught** when we deploy a version with github actions. This is, of course, wrong... Therefore, the github actions should add a test for building the site, that might fail when there are javadoc errors:

```yaml
    - name: Build with Maven and check if site building works
      run: mvn clean site --file pom.xml

    - name: Build with Maven and test if signing works
      run: mvn clean package -P release --file pom.xml
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
```

2) The site building process has changed, and `site.xml` needs an explicit skin. The `site.xml` files has to be updated with:

```xml
  <skin>
    <groupId>org.apache.maven.skins</groupId>
    <artifactId>maven-fluido-skin</artifactId>
    <version>2.0.0-M8</version>
  </skin>
```

3) `${artifactId}` and ${version} do not work anymore and has to be preceded with `project.`. The project tag in `site.xml` therefore has to start with:

```xml
<project name="${project.artifactId} ${project.version}"
```

4) headers have changed. Make them explicit with:

```xml
  <bannerLeft>
    <name>${project.name}</name>
  </bannerLeft>

  <bannerRight>
    <name>${project.artifactId} ${project.version}</name>
  </bannerRight>
```
